### ISSUE TITLE
Contract Spec: Include host function, sdk, env versions in WASM

### ISSUE THREAD

**Issue by graydon** [stellar/rs-stellar-contract-sdk#142]
The change https://github.com/stellar/rs-stellar-contract-env/pull/120 renamed host functions. This is fine and we're still iterating and I'm not upset about it but it broke existing wasm blobs (eg. those embedded in tests) that expected the old host function names to exist.

This revealed / reveals a thing I think we should probably encode in contracts: the host function API version they were compiled against. Not because I expect we'll multi-version the API surface or anything -- I expect long-term we'll commit to a strictly backward-compatible API unless there are dangerous bugs -- but because I think @jonjove spent a while hunting the bug and it would be better to give concise diagnostics for such mismatches (new contract running on old host, or compatibility break for whatever reason) during contract instantiation rather than failing inscrutably during execution.

So I think we should have "the version of the host you were compiled against" as metadata pasted into yet another custom section in the wasm (or in the spec section if you can include it there, I don't care).

**Comment by leighmcculloch** [comment]
💯 It should be trivial to include this in a custom section we just need to decide how we version the host API. For example, will this be a hard coded constant we manually bump? or automatically generated somehow by the host API macros? 

This is also one reason why the CLI has an [inspect](https://github.com/stellar/stellar-contract-cli/blob/main/src/inspect.rs) sub-command, so that we can quickly pull up info about a WASM file and we can expose this information there. In the [SJC](https://github.com/leighmcculloch/sjc) prototype we would output the imports (dependencies) too, and we can add that to inspect that should help with debugging.

>it would be better to give concise diagnostics for such mismatches (new contract running on old host, or compatibility break for whatever reason) during contract instantiation

Actually, the host VM could do this today without introducing any version meta into WASM files. We could add validation into the host VM that compares the required imports with the available imports and displays a well formed error stating exactly which imports are missing. Ideally the host isn't erroring generically in this situation.

**Comment by leighmcculloch** [comment]
```
❯ stellar-contract-cli inspect --file target/wasm32-unknown-unknown/release/example_udt.wasm
File: target/wasm32-unknown-unknown/release/example_udt.wasm
Functions:
 • add (val, val) -> (res)
Env Meta: AAAAAAAAAAAAAAAB
 • Interface Version: 1
```
